rvm: '2.3.1'
script:
  - mkdir -p spec && bundle exec rspec spec
before_install:
- sed -i '2d' Gemfile
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
before_script:
  - psql -c 'create database Brim_final_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 3

language: node_js
node_js:
  - '4.4'

script:
  - node_modules/.bin/karma start spec/javasripts/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor spec/javasripts/protractor.conf.js --browser=firefox
